# fly.toml app configuration file generated for damp-mountain-7086 on 2023-08-01T11:27:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-mountain-7086"
primary_region = "eze"


[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  restart_limit = 0
  timeout = 3000
  tls_skip_verify = false
  [services.http_checks.headers]